# Uncomment the next line to define a global platform for your project
  platform :ios, '15.5'

target 'Houstay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Houstay

  pod 'R.swift'
  pod 'SnapKit'
  pod 'KeychainSwift'
  pod 'RealmSwift'
  pod 'Firebase' 
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseCore'
  pod 'FirebaseDatabase' 
  pod 'GoogleSignIn'
    
end

# Disable signing for pods
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
         end
    end
  end
end